#!/bin/bash

for tmpU in $(seq 2.1  0.1  3.6)
do 
    mkdir U$tmpU && cd U$tmpU
    cp ../Generate_disBatch_Input_File.py Generate_disBatch_Input_File.py

    # Linux version
    sed -i "s/Submission_U2.0/Submission_U$tmpU/g" Generate_disBatch_Input_File.py 

    # # MacOS version
    # sed -i "" "s/Submission_U2.0/Submission_U$tmpU/g" Generate_disBatch_Input_File.py 
    
    python3 Generate_disBatch_Input_File.py

    for tmpBeta in $(seq 2.0  0.1  50.0)
    do 
        mkdir beta$tmpBeta
        cp ../Unrestricted_Hartree_Fock.f90 beta$tmpBeta/Unrestricted_Hartree_Fock.f90
        
        cd beta$tmpBeta
            # Linux version
            sed -i "s/U=2.0/U=$tmpU/g" Unrestricted_Hartree_Fock.f90
            sed -i "s/beta=2.0/beta=$tmpBeta/g" Unrestrcited_Hartree_Fock.f90
            
            # # MacOS version
            # sed -i "" "s/U=2.0/U=$tmpU/g" Unrestricted_Hartree_Fock.f90
            # sed -i "" "s/beta=2.0/beta=$tmpBeta/g" Unrestricted_Hartree_Fock.f90  
        
            ifort -mkl Unrestricted_Hartree_Fock.f90 -o UHF.o  
        cd .. 
    done

    # # # Job submission on rusty
    # # sbatch -n 250 -c 8 -t 7-0:0:0 -p ccq --constraint=rome disBatch T$time

    # Job submission on popeye
    sbatch -n 481 -c 1 -t 7-0:0:0 -p ccq --constraint=cascadelake disBatch Submission_U$tmpU
    cd ..
done